### Collection GET
GET http://localhost:3000/tasks
Accept: application/json
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7, fr-FR
x-api-version: v1

### Collection POST
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Dormir"
}

### Item GET
GET http://localhost:3000/tasks/1
Accept : text/xml

### Item PUT : replace
PUT http://localhost:3000/tasks/1
Content-type: application/json

{
  "title": "Manger"
}

### Item Put : create
PUT http://localhost:3000/tasks/-1
Content-type: application/json

{
  "title": "Travailler",
  "completed": true
}

### Item PATCH 
PATCH http://localhost:3000/tasks/1
Content-type: application/json

{
  "completed": true
}

### Item DELETE
DELETE http://localhost:3000/tasks/-1
